### ISSUE TITLE
Collision Export Issue?

### ISSUE THREAD

**Issue by wytman71** [tobi-be/BlenderEdmExporter#18]
Collision Export seems to cause an error.  I reverted to 1.04 with my model and it exports fine.  Is there a change required?

**Comment by wytman71** [comment]
[Sandy FARP.zip](https://github.com/tobi-be/BlenderEdmExporter/files/6127759/Sandy.FARP.zip)

**Comment by wytman71** [comment]
![image](https://user-images.githubusercontent.com/79193418/110896068-73057000-82c0-11eb-94b9-749f73cdaa64.png)

**Comment by tobi-be** [comment]
Hi thank you for your report. There was a bug. You can download a bugfixed version of the edmexporter- file and replace it in your addon folder.

**Comment by WatchBambi** [comment]
Hey, first off I want to thank you for this amazing exporter! Unfortunately, I've also run into an issue trying to export the collision model. It's all correctly parented to the root armature and subsequently set up as a SegmentNode. In my case, it seems to export fine without any errors but doesn't show up in modelviewer. I am using the latest version (1.0.6) in blender 2.83.5 and have also tried it in 2.8 without success.

**Comment by tobi-be** [comment]
Try this example. it works fine with at least with 2.91. Collision lines are not shown by default in the modelviewer. You have to enable it: Show -> Model Shell->Something with Line

[collisionexample.zip](https://github.com/tobi-be/BlenderEdmExporter/files/6489218/collisionexample.zip)

**Comment by WatchBambi** [comment]
Thank you for taking the time to create an example, it seems that my edm was set up correctly. I managed to sort it out and it mostly was user error (collision model not properly aligned) and modelviewer acting up. In case anyone else hits the same wall that I had. Make sure to use Tobi his way to show the collision, the red button (show model collision) in modelviewer seems to be broken.

**Comment by bobgreen933** [comment]
Hello. Thank you for this great addon. Unfortunately  it is not working correctly since updating DCS to 2.7. Prior to update, I could export a simple box attached to an armature. I could replace the AH-6.edm from the AH-6J_V0.4 mod and it would fly correctly. After update, as soon as mission starts, it sinks underground. I have tried on different computers and a fresh install of everything, no luck. After much googling, this does not seem to be a common issue. One thing I found interesting. Anything I did find on google suggested issues with collision lines, meshes, boxes, etc. In previous DCS version, my model worked without any of that. The AH-6 mod does have an AH-6_collision.edm. I assumed that was all I needed and it did fly well without submerging. I have spent days troubleshooting this but I am stumped.

**Comment by tobi-be** [comment]
Hi, I am pretty shure that this is not a problem of the exporter. If you just export a simple cube, there are no collision-elements and it is clean that a collision does not work.

**Comment by bobgreen933** [comment]
Good old DCS. They like to break things that previously worked, lol. So are collision lines in the main model.edm and a model_collision.edm both required or does either alone cover it? Is sinking into the ground and colliding with other objects considered the same thing ingame?
